# Dockerhub workflow

name: TechTrends - Package with Docker
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions v2
        uses: actions/checkout@v2
      - name: QEMU Set up
        uses: docker/setup-qemu-action@v2
      - name: Docker Buildx Set up
        uses: docker/setup-buildx-action@v2
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: project/techtrends/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:latest
