# Dockerhub workflow

name: TechTrends - Package with Docker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      -
        name: Checkout actions v2
        uses: actions/checkout@v2
      -
        name: QEMU Set up
        uses: docker/setup-qemu-action@v1
      -
        name: Docker Buildx Set up
        uses: docker/setup-buildx-action@v1
      -
        name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./techtrends/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/techtrends:latest

